# Generated by Django 4.2.24 on 2025-09-06 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_type', models.CharField(choices=[('job_application', 'Отклик на вакансию'), ('course_enrollment', 'Запись на курс')], max_length=20, verbose_name='Тип клика')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время клика')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Курс')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.job', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Событие клика',
                'verbose_name_plural': 'События кликов',
                'ordering': ['-timestamp'],
            },
        ),
    ]
