# Generated by Django 4.2.24 on 2025-09-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Слаг')),
                ('excerpt', models.TextField(blank=True, verbose_name='Анонс')),
                ('content', models.TextField(verbose_name='Полный текст')),
                ('cover_image', models.ImageField(blank=True, upload_to='blog/covers/', verbose_name='Обложка')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-published_at'],
            },
        ),
    ]
